"""
AI Code Review Agent - Main Entry Point

Usage:
    python code_review_main.py review <file.py>              # Review a file
    python code_review_main.py review <folder/>              # Review all .py files
    python code_review_main.py index                         # Index knowledge base
    python code_review_main.py evaluate <codereview.md>      # Evaluate a review

Options:
    --output-dir DIR        Output directory (default: ./code_review_output)
    --no-reflection         Disable self-reflection
    --no-validation         Disable sandbox validation
    --complexity LEVEL      LLM complexity: low/medium/high (default: medium)
    --dry-run               Show what would be done without executing
"""

import argparse
import sys
import os
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent))

from code_review.agent import CodeReviewAgent, AgentConfig, create_agent
from code_review.evaluator import ReviewEvaluator


def _generate_final_summary(agent, results, output_dir):
    """Append a final summary table to codereview.md."""
    if not results:
        return
    
    output_path = Path(output_dir) / "codereview.md"
    if not output_path.exists():
        return
    
    # Calculate totals
    total_issues = sum(len(r.issues) for r in results)
    avg_confidence = sum(r.confidence for r in results) / len(results)
    corrected_count = sum(1 for r in results if r.corrected_code)
    
    # Build summary table
    summary = f"""

---

# 📊 Full Review Summary

**Command Completed:** {len(results)} files reviewed  
**Generated:** {results[0].timestamp if results else 'N/A'}

## Statistics

| Metric | Value |
|--------|-------|
| **Total Files** | {len(results)} |
| **Total Issues** | {total_issues} |
| **Corrected Files** | {corrected_count} |
| **Average Confidence** | {avg_confidence:.1%} |

## Files Reviewed

| File | Issues | Confidence | Corrected |
|------|--------|------------|-----------|
"""
    
    for r in results:
        filename = Path(r.file_path).name
        corrected = "✅" if r.corrected_code else "❌"
        summary += f"| `{filename}` | {len(r.issues)} | {r.confidence:.0%} | {corrected} |\n"
    
    summary += """
---

*Generated by AI Code Review Agent*
"""
    
    # Append to existing file
    existing = output_path.read_text(encoding='utf-8')
    output_path.write_text(existing + summary, encoding='utf-8')


def main():
    parser = argparse.ArgumentParser(
        description="AI Code Review and Correction Agent",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python code_review_main.py review ./my_code.py
    python code_review_main.py review ./src/ --output-dir ./reviews
    python code_review_main.py index --data-dir ./Data/python
    python code_review_main.py evaluate ./code_review_output/codereview.md
        """
    )
    
    subparsers = parser.add_subparsers(dest="command", help="Available commands")
    
    # Review command
    review_parser = subparsers.add_parser("review", help="Review Python code")
    review_parser.add_argument("path", help="Path to file or folder to review")
    review_parser.add_argument("--output-dir", default="./code_review_output",
                               help="Output directory")
    review_parser.add_argument("--no-reflection", action="store_true",
                               help="Disable self-reflection")
    review_parser.add_argument("--no-validation", action="store_true",
                               help="Disable sandbox validation")
    review_parser.add_argument("--complexity", choices=["low", "medium", "high"],
                               default="medium", help="LLM complexity level")
    review_parser.add_argument("--dry-run", action="store_true",
                               help="Show what would be done")
    
    # Index command
    index_parser = subparsers.add_parser("index", help="Index knowledge base")
    index_parser.add_argument("--data-dir", default="./Data/python",
                              help="Directory containing knowledge base files")
    index_parser.add_argument("--persist-dir", default="./chroma_db",
                              help="Vector database directory")
    index_parser.add_argument("--reindex", action="store_true",
                              help="Force reindex all documents")
    
    # Evaluate command
    evaluate_parser = subparsers.add_parser("evaluate", help="Evaluate a review")
    evaluate_parser.add_argument("review_path", help="Path to codereview.md")
    evaluate_parser.add_argument("--reference", help="Path to reference review for comparison")
    
    # Demo command
    demo_parser = subparsers.add_parser("demo", help="Run demo with sample bad code")
    demo_parser.add_argument("--output-dir", default="./code_review_output",
                            help="Output directory")
    
    # Review changes command (git diff)
    changes_parser = subparsers.add_parser("review-changes", help="Review uncommitted changes")
    changes_parser.add_argument("--staged", action="store_true",
                               help="Only review staged changes")
    changes_parser.add_argument("--output-dir", default="./code_review_output",
                               help="Output directory")
    changes_parser.add_argument("--no-reflection", action="store_true",
                               help="Disable self-reflection")
    
    # Review commit command
    commit_parser = subparsers.add_parser("review-commit", help="Review a specific commit")
    commit_parser.add_argument("commit", help="Commit hash to review")
    commit_parser.add_argument("--output-dir", default="./code_review_output",
                              help="Output directory")
    commit_parser.add_argument("--no-reflection", action="store_true",
                              help="Disable self-reflection")
    
    # Review PR command
    pr_parser = subparsers.add_parser("review-pr", help="Review a GitHub Pull Request")
    pr_parser.add_argument("pr_number", type=int, help="Pull Request number")
    pr_parser.add_argument("--repo", required=True, help="Repository (owner/repo)")
    pr_parser.add_argument("--output-dir", default="./code_review_output",
                          help="Output directory")
    pr_parser.add_argument("--post-comment", action="store_true",
                          help="Post review as PR comment")
    pr_parser.add_argument("--no-reflection", action="store_true",
                          help="Disable self-reflection")
    
    args = parser.parse_args()
    
    if args.command is None:
        parser.print_help()
        return 0
    
    if args.command == "review":
        return cmd_review(args)
    elif args.command == "index":
        return cmd_index(args)
    elif args.command == "evaluate":
        return cmd_evaluate(args)
    elif args.command == "demo":
        return cmd_demo(args)
    elif args.command == "review-changes":
        return cmd_review_changes(args)
    elif args.command == "review-commit":
        return cmd_review_commit(args)
    elif args.command == "review-pr":
        return cmd_review_pr(args)
    
    return 0


def cmd_review(args):
    """Handle review command."""
    path = Path(args.path)
    
    if not path.exists():
        print(f"Error: Path not found: {args.path}")
        return 1
    
    if args.dry_run:
        print(f"[DRY RUN] Would review: {path}")
        print(f"[DRY RUN] Output directory: {args.output_dir}")
        print(f"[DRY RUN] Reflection: {'disabled' if args.no_reflection else 'enabled'}")
        print(f"[DRY RUN] Validation: {'disabled' if args.no_validation else 'enabled'}")
        print(f"[DRY RUN] Complexity: {args.complexity}")
        return 0
    
    # Create agent
    config = AgentConfig(
        output_dir=args.output_dir,
        use_reflection=not args.no_reflection,
        validate_fixes=not args.no_validation,
        default_complexity=args.complexity
    )
    
    # Try to load RAG retriever if available
    rag_retriever = None
    try:
        from rag_chatbot.chatbot import RAGChatbot
        from rag_chatbot.retriever import Retriever
        
        # Check if vector database exists
        if Path("./chroma_db").exists():
            print("Loading RAG knowledge base...")
            chatbot = RAGChatbot(
                data_directory="./Data/python",
                persist_directory="./chroma_db",
                collection_name="python_best_practices"
            )
            rag_retriever = chatbot.retriever
            print("✓ RAG knowledge base loaded")
    except Exception as e:
        print(f"Note: RAG not available ({e}). Using default best practices.")
    
    agent = CodeReviewAgent(config=config, rag_retriever=rag_retriever)
    
    # Clear previous output before starting new review
    agent.tools.clear_output()
    print("✓ Cleared previous output files")
    
    # Review
    if path.is_file():
        result = agent.review_file(str(path))
        print(f"\n✓ Review complete!")
        print(f"  Issues found: {len(result.issues)}")
        print(f"  Score: {result.overall_score}/10")
        print(f"  Confidence: {result.confidence:.1%}")
        print(f"  Report: {args.output_dir}/codereview.md")
    else:
        # Review folder with append mode
        all_results = []
        folder = Path(path)
        py_files = [f for f in folder.rglob("*.py") 
                    if "__pycache__" not in str(f) and "venv" not in str(f)]
        
        for i, py_file in enumerate(py_files):
            result = agent.review_file(str(py_file), append_report=(i > 0))
            all_results.append(result)
        
        # Generate summary
        _generate_final_summary(agent, all_results, args.output_dir)
        
        print(f"\n✓ Reviewed {len(all_results)} files")
        total_issues = sum(len(r.issues) for r in all_results)
        print(f"  Total issues: {total_issues}")
        print(f"  Reports: {args.output_dir}/")
    
    return 0


def cmd_index(args):
    """Handle index command."""
    data_dir = Path(args.data_dir)
    
    if not data_dir.exists():
        print(f"Error: Data directory not found: {args.data_dir}")
        return 1
    
    print(f"Indexing knowledge base from: {data_dir}")
    
    try:
        from rag_chatbot.chatbot import RAGChatbot
        
        chatbot = RAGChatbot(
            data_directory=str(data_dir),
            persist_directory=args.persist_dir,
            collection_name="python_best_practices",
            chunk_size=500,
            chunk_overlap=50
        )
        
        num_chunks = chatbot.index_documents(force_reindex=args.reindex)
        print(f"✓ Indexed {num_chunks} chunks from knowledge base")
        print(f"  Persist directory: {args.persist_dir}")
        
    except Exception as e:
        print(f"Error indexing: {e}")
        return 1
    
    return 0


def cmd_evaluate(args):
    """Handle evaluate command."""
    review_path = Path(args.review_path)
    
    if not review_path.exists():
        print(f"Error: Review not found: {args.review_path}")
        return 1
    
    evaluator = ReviewEvaluator()
    
    print(f"Evaluating review: {review_path}")
    
    # Simple heuristic evaluation based on review content
    review_content = review_path.read_text(encoding='utf-8')
    
    # Count issues mentioned
    import re
    issue_count = len(re.findall(r'###\s+Line\s+\d+', review_content))
    
    # Create dummy issues for evaluation
    review_issues = [
        {"line": i, "severity": "major", "message": f"Issue {i}", 
         "suggestion": "Fix it", "rule_reference": f"RULE_{i}"}
        for i in range(1, issue_count + 1)
    ]
    
    result = evaluator.evaluate_synthetic(
        review_issues=review_issues,
        static_issues=review_issues,  # Assume same for synthetic
        code="# evaluation mode"
    )
    
    print(f"\n{'='*50}")
    print("Evaluation Results")
    print(f"{'='*50}")
    print(f"  Accuracy:      {result.scores.accuracy:.1f}/5")
    print(f"  Relevance:     {result.scores.relevance:.1f}/5")
    print(f"  Clarity:       {result.scores.clarity:.1f}/5")
    print(f"  Actionability: {result.scores.actionability:.1f}/5")
    print(f"  Overall:       {result.scores.overall:.1f}/5")
    print(f"{'='*50}")
    
    # Generate report
    report_path = evaluator.generate_report(
        str(review_path.parent / "evaluation_report.md")
    )
    print(f"\n✓ Evaluation report saved: {report_path}")
    
    return 0


def cmd_demo(args):
    """Run demo with sample bad code."""
    print("="*60)
    print("  AI Code Review Agent - Demo")
    print("="*60)
    
    # Sample bad code
    demo_code = '''"""A module with intentionally bad code for demo purposes."""

import os
import sys
import json  # Unused import

password = "super_secret_123"  # Hardcoded secret!
api_key = "sk-abc123xyz"

def process_user_data(user_id, items=[]):
    """Process user data with several issues."""
    global total_count
    total_count = 0
    
    # SQL Injection vulnerability
    query = f"SELECT * FROM users WHERE id = {user_id}"
    cursor.execute(query)
    
    # Deep nesting
    for item in items:
        if item:
            if item.active:
                if item.valid:
                    if item.ready:
                        print(item)  # Should use logging
                        total_count += 1
    
    # TODO: Add proper error handling
    try:
        result = risky_operation()
    except:  # Bare except
        pass  # Silent failure
    
    return result

def calculate_something(x):
    # Magic number
    return x * 3.14159 * 42 + 12345

class DataProcessor:
    def process(self, data):
        if data != None:  # Should use 'is not None'
            if data.value != None:
                print(data.value)
'''
    
    # Save demo code
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    demo_file = output_dir / "demo_bad_code.py"
    demo_file.write_text(demo_code, encoding='utf-8')
    
    print(f"\n✓ Demo code saved to: {demo_file}")
    print("\nRunning code review on demo file...\n")
    
    # Try to load RAG retriever if available
    rag_retriever = None
    try:
        from rag_chatbot.chatbot import RAGChatbot
        if Path("./chroma_db").exists():
            print("Loading RAG knowledge base...")
            chatbot = RAGChatbot(
                data_directory="./Data/python",
                persist_directory="./chroma_db",
                collection_name="python_best_practices"
            )
            rag_retriever = chatbot.retriever
            print("✓ RAG knowledge base loaded (PDFs + Videos)")
    except Exception as e:
        print(f"Note: RAG not available ({e}). Using default best practices.")
    
    # Create agent with reflection disabled for faster demo
    config = AgentConfig(
        output_dir=str(output_dir),
        use_reflection=False,  # Faster for demo
        validate_fixes=True
    )
    
    agent = CodeReviewAgent(config=config, rag_retriever=rag_retriever)
    result = agent.review_file(str(demo_file))
    
    print("\n" + "="*60)
    print("  Demo Complete!")
    print("="*60)
    print(f"\n  Issues found: {len(result.issues)}")
    print(f"  Score: {result.overall_score}/10")
    print(f"  Confidence: {result.confidence:.1%}")
    print(f"\n  Output files:")
    print(f"    - {output_dir}/codereview.md")
    print(f"    - {output_dir}/audit_log.json")
    if result.corrected_code:
        print(f"    - {output_dir}/corrected_demo_bad_code.py")
    
    return 0


def cmd_review_changes(args):
    """Review uncommitted changes (git diff)."""
    from code_review.git_integration import GitIntegration
    
    print("=" * 60)
    print("  Review Uncommitted Changes")
    print("=" * 60)
    
    try:
        git = GitIntegration(".")
        files = git.get_changed_files(staged_only=args.staged)
        
        if not files:
            print("\n✓ No Python files changed")
            return 0
        
        print(f"\nFound {len(files)} changed Python file(s):")
        for f in files:
            status_map = {'M': 'modified', 'A': 'added', 'D': 'deleted'}
            print(f"  [{status_map.get(f.status, f.status)}] {f.path}")
        
        # Review each file
        output_dir = Path(args.output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        
        # Load RAG
        rag_retriever = None
        try:
            from rag_chatbot.chatbot import RAGChatbot
            if Path("./chroma_db").exists():
                print("\nLoading RAG knowledge base...")
                chatbot = RAGChatbot(
                    data_directory="./Data/python",
                    persist_directory="./chroma_db",
                    collection_name="python_best_practices"
                )
                rag_retriever = chatbot.retriever
        except Exception:
            pass
        
        config = AgentConfig(
            output_dir=str(output_dir),
            use_reflection=not args.no_reflection,
            validate_fixes=True
        )
        agent = CodeReviewAgent(config=config, rag_retriever=rag_retriever)
        
        # Clear previous output before starting
        agent.tools.clear_output()
        print("✓ Cleared previous output files")
        
        all_results = []
        for i, f in enumerate(files):
            if f.status != 'D':  # Skip deleted files
                file_path = Path(f.path)
                if file_path.exists():
                    print(f"\n--- Reviewing: {f.path} ---")
                    # Append to report for all files after the first
                    result = agent.review_file(str(file_path), append_report=(i > 0))
                    all_results.append(result)
        
        # Generate final summary
        _generate_final_summary(agent, all_results, str(output_dir))
        
        print("\n" + "=" * 60)
        print("  Review Complete!")
        print("=" * 60)
        print(f"\n  Files reviewed: {len(all_results)}")
        print(f"  Output: {output_dir}/codereview.md")
        
        return 0
        
    except Exception as e:
        print(f"Error: {e}")
        return 1


def cmd_review_commit(args):
    """Review files changed in a specific commit."""
    from code_review.git_integration import GitIntegration
    
    print("=" * 60)
    print(f"  Review Commit: {args.commit}")
    print("=" * 60)
    
    try:
        git = GitIntegration(".")
        files = git.get_commit_files(args.commit)
        
        if not files:
            print("\n✓ No Python files in this commit")
            return 0
        
        print(f"\nFound {len(files)} Python file(s) in commit:")
        for f in files:
            print(f"  [{f.status}] {f.path}")
        
        # Review each file
        output_dir = Path(args.output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        
        # Load RAG
        rag_retriever = None
        try:
            from rag_chatbot.chatbot import RAGChatbot
            if Path("./chroma_db").exists():
                print("\nLoading RAG knowledge base...")
                chatbot = RAGChatbot(
                    data_directory="./Data/python",
                    persist_directory="./chroma_db",
                    collection_name="python_best_practices"
                )
                rag_retriever = chatbot.retriever
        except Exception:
            pass
        
        config = AgentConfig(
            output_dir=str(output_dir),
            use_reflection=not args.no_reflection,
            validate_fixes=True
        )
        agent = CodeReviewAgent(config=config, rag_retriever=rag_retriever)
        
        # Clear previous output before starting
        agent.tools.clear_output()
        print("✓ Cleared previous output files")
        
        all_results = []
        for i, f in enumerate(files):
            if f.status != 'D':
                file_path = Path(f.path)
                if file_path.exists():
                    print(f"\n--- Reviewing: {f.path} ---")
                    # Append to report for all files after the first
                    result = agent.review_file(str(file_path), append_report=(i > 0))
                    all_results.append(result)
        
        # Generate final summary
        _generate_final_summary(agent, all_results, str(output_dir))
        
        print("\n" + "=" * 60)
        print("  Commit Review Complete!")
        print("=" * 60)
        print(f"  Files reviewed: {len(all_results)}")
        print(f"  Output: {output_dir}/codereview.md")
        
        return 0
        
    except Exception as e:
        print(f"Error: {e}")
        return 1


def cmd_review_pr(args):
    """Review a GitHub Pull Request."""
    from code_review.git_integration import GitHubIntegration
    import tempfile
    
    print("=" * 60)
    print(f"  Review Pull Request #{args.pr_number}")
    print(f"  Repository: {args.repo}")
    print("=" * 60)
    
    try:
        gh = GitHubIntegration()
        
        # Get PR info
        pr_info = gh.get_pr_info(args.repo, args.pr_number)
        print(f"\n  Title: {pr_info['title']}")
        print(f"  Author: {pr_info['author']}")
        print(f"  Branch: {pr_info['head_branch']} → {pr_info['base_branch']}")
        print(f"  Files: {pr_info['files_count']} (+{pr_info['additions']}/-{pr_info['deletions']})")
        
        # Get changed files
        files = gh.get_pr_files(args.repo, args.pr_number)
        python_files = [f for f in files if f.path.endswith('.py')]
        
        if not python_files:
            print("\n✓ No Python files in this PR")
            return 0
        
        print(f"\nFound {len(python_files)} Python file(s):")
        for f in python_files:
            print(f"  [{f.status}] {f.path}")
        
        # Setup output
        output_dir = Path(args.output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        
        # Load RAG
        rag_retriever = None
        try:
            from rag_chatbot.chatbot import RAGChatbot
            if Path("./chroma_db").exists():
                print("\nLoading RAG knowledge base...")
                chatbot = RAGChatbot(
                    data_directory="./Data/python",
                    persist_directory="./chroma_db",
                    collection_name="python_best_practices"
                )
                rag_retriever = chatbot.retriever
        except Exception:
            pass
        
        config = AgentConfig(
            output_dir=str(output_dir),
            use_reflection=not args.no_reflection,
            validate_fixes=True
        )
        agent = CodeReviewAgent(config=config, rag_retriever=rag_retriever)
        
        # Clear previous output before starting
        agent.tools.clear_output()
        print("✓ Cleared previous output files")
        
        # Review each file
        all_results = []
        for i, f in enumerate(python_files):
            if f.status != 'D':
                print(f"\n--- Reviewing: {f.path} ---")
                
                # Get file content from PR
                content = gh.get_file_content_from_pr(args.repo, args.pr_number, f.path)
                
                if content:
                    # Save to temp file for review
                    with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False) as tmp:
                        tmp.write(content)
                        tmp_path = tmp.name
                    
                    # Append to report for all files after the first
                    result = agent.review_file(tmp_path, append_report=(i > 0))
                    all_results.append(result)
                    
                    # Cleanup
                    Path(tmp_path).unlink()
        
        # Generate final summary
        _generate_final_summary(agent, all_results, str(output_dir))
        
        # Generate summary
        report_path = output_dir / "codereview.md"
        
        print("\n" + "=" * 60)
        print("  PR Review Complete!")
        print("=" * 60)
        print(f"  Files reviewed: {len(all_results)}")
        print(f"  Report: {report_path}")
        print(f"  PR URL: {pr_info['url']}")
        
        # Post comment to PR if requested
        if args.post_comment and report_path.exists():
            print("\nPosting review comment to PR...")
            report_content = report_path.read_text()
            # Truncate if too long
            if len(report_content) > 60000:
                report_content = report_content[:60000] + "\n\n... (truncated)"
            
            comment = f"## 🤖 AI Code Review\n\n{report_content}"
            if gh.post_pr_comment(args.repo, args.pr_number, comment):
                print("✓ Review posted to PR")
            else:
                print("✗ Failed to post comment")
        
        return 0
        
    except Exception as e:
        print(f"Error: {e}")
        return 1


if __name__ == "__main__":
    sys.exit(main())

